name: Build
on: [workflow_dispatch]

jobs:
  build32:
    name: 32-bit build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        env:
          DEBIAN_FRONTEND: non-interactive
        run: "sudo apt update && sudo apt install -y build-essential make gcc gcc-multilib g++ mingw-w64 mingw-w64-common mingw-w64-tools mingw-w64-i686-dev mingw-w64-x86-64-dev"

      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.30.5

      - name: Prepare build
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="mingw32.cmake"
      
      - name: "Build"
        run: "cmake --build build --target love --config Release -j2"