name: build
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [Win32, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: megasource
    - name: Checkout LÖVE
      uses: actions/checkout@v2
      with:
        path: megasource/libs/love
        repository: love2d/love
        ref: main
    - name: Configure
      shell: cmd
      env:
        PLATFORM: ${{ matrix.platform }}
      run: cmake -Bbuild -Hmegasource -T v142 -A %PLATFORM% -DCMAKE_INSTALL_PREFIX=%CD%\install
    - name: Install
      shell: cmd
      run: cmake --build build --config Release --target install -j2
